[IMP] state: add model `Property` T#69469
Suavesito-Olimpiada/technical-training-odoo pull request #3
Opened 2023-03-16 20:44 UTC by Suavesito-Olimpiada

@deivislaya 

This PR is ready for review, it implements section 4 of _Getting Started_.

Regards!

2023-03-21 18:31 UTC, deivislaya commented
Please. Rebase this MR

2023-03-21 19:48 UTC, deivislaya requested changes

2023-03-21 19:48 UTC, deivislaya commented on estate/models/estate_property.py
> +    name = fields.Char(required=True)
Please, add help attribute in the field. Review all ocurrences

2023-03-21 19:48 UTC, deivislaya commented on estate/models/estate_property.py
> +        [("north", "North"), ("south", "South"), ("east", "East"), ("west", "West")]
```suggestion
        selection=[("north", "North"), ("south", "South"), ("east", "East"), ("west", "West")]
```

2023-03-22 02:58 UTC, Suavesito-Olimpiada commented on estate/models/estate_property.py
> +    name = fields.Char(required=True)
Do I add help for all fields or just name? In #5 I add label string for those who need it, based on the model from the documentation.

2023-03-22 03:04 UTC, Suavesito-Olimpiada commented on estate/models/estate_property.py
> +        [("north", "North"), ("south", "South"), ("east", "East"), ("west", "West")]
Correction made.

2023-03-22 22:42 UTC, deivislaya commented on estate/models/estate_property.py
> +    name = fields.Char(required=True)
In all fields

2023-03-24 01:15 UTC, deivislaya commented on estate/models/estate_property.py
> +    name = fields.Char(required=True)
change pending

2023-03-28 07:58 UTC, Suavesito-Olimpiada commented on estate/models/estate_property.py
> +    name = fields.Char(required=True)
Solved.

2023-03-28 16:29 UTC, deivislaya approved these changes

2023-03-28 16:30 UTC, merged